# Generated by Django 4.2.16 on 2026-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=254, null=True)),
                ('collaboration_type', models.CharField(choices=[('guest_blog', 'Guest Blog'), ('workshop', 'Workshop/Event'), ('product_review', 'Product Review'), ('partnership', 'Business Partnership'), ('other', 'Other')], default='other', max_length=50)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='collaborations/')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Under Review'), (2, 'Accepted'), (3, 'Declined')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
