# Generated by Django 4.2.16 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
