# Generated by Django 4.2.16 on 2026-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
