# Generated by Django 4.2.16 on 2026-04-12 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_contraindications_service_preparation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('customer_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending Payment'), (1, 'Confirmed'), (2, 'Completed'), (3, 'Cancelled')], default=0)),
                ('stripe_pid', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', '-time_slot'],
                'unique_together': {('booking_date', 'time_slot', 'service')},
            },
        ),
    ]
